const sampleListings = [
  {
    title: "The Taj Hotel",
    description: "Luxury hotel with sea view, located near the Gateway of India.",
    image: "https://images.unsplash.com/photo-1582719478173-2d42e7d52f85",
    price: 12000,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Mountain Retreat",
    description: "Cozy cottage surrounded by Himalayan mountains.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 6000,
    location: "Manali",
    country: "India",
  },
  {
    title: "Desert Oasis Camp",
    description: "Luxury desert camp experience with camel rides and stargazing.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 3500,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Urban Studio Apartment",
    description: "Compact studio apartment ideal for business travelers.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 4500,
    location: "Bengaluru",
    country: "India",
  },
  {
    title: "Goa Beach Resort",
    description: "Tropical resort with pool and private beach access.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    price: 7000,
    location: "Goa",
    country: "India",
  },
  {
    title: "Lake View Cabin",
    description: "Wooden cabin with a scenic view of the lake.",
    image: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2a06",
    price: 5000,
    location: "Nainital",
    country: "India",
  },
  {
    title: "City Center Hotel",
    description: "Premium hotel in the heart of the city with rooftop dining.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    price: 8500,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Tea Garden Villa",
    description: "Beautiful villa located amidst tea plantations.",
    image: "https://images.unsplash.com/photo-1591081948333-10fc28b1a69b",
    price: 5500,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Riverside Cottage",
    description: "Tranquil stay beside a flowing river, perfect for couples.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    price: 4000,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Snowy Chalet",
    description: "Warm and cozy chalet in the snowy valleys.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 9500,
    location: "Shimla",
    country: "India",
  },
   {
    title: "Luxury Palace Stay",
    description: "Stay in a royal palace converted into a 5-star heritage hotel.",
    image: "https://images.unsplash.com/photo-1501117716987-c8e1ecb2101f",
    price: 15000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Houseboat Paradise",
    description: "Charming houseboat with all modern amenities on the backwaters.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 8000,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Forest Treehouse",
    description: "Live among the trees with panoramic forest views.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 6500,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Countryside Homestay",
    description: "Simple and peaceful homestay with home-cooked meals.",
    image: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba",
    price: 3000,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Island View Villa",
    description: "Seaside villa with breathtaking views and infinity pool.",
    image: "https://images.unsplash.com/photo-1522156373667-4c7234bbd804",
    price: 11000,
    location: "Andaman Islands",
    country: "India",
  },
  {
    title: "Desi Farmhouse",
    description: "Traditional Indian farmhouse surrounded by green fields.",
    image: "https://images.unsplash.com/photo-1597095247098-8b04c52b3f59",
    price: 4500,
    location: "Punjab",
    country: "India",
  },
  {
    title: "Skyline Penthouse",
    description: "Ultra-modern penthouse with city skyline view and jacuzzi.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 18000,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Vintage Haveli",
    description: "Restored haveli with antique furniture and cultural vibes.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 9500,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Hilltop Bungalow",
    description: "Breathtaking view from a peaceful hilltop home.",
    image: "https://images.unsplash.com/photo-1600585154207-9b9a3b66b8e3",
    price: 7200,
    location: "Kodaikanal",
    country: "India",
  },
  {
    title: "Seaside Apartment",
    description: "Relaxed apartment near the beach with ocean breeze.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 5500,
    location: "Vizag",
    country: "India",
  },
  {
    title: "Luxury Tent Stay",
    description: "Glamorous tent stay with bonfire and open-air dining.",
    image: "https://images.unsplash.com/photo-1534067783941-51c9c23a4c4b",
    price: 4800,
    location: "Pushkar",
    country: "India",
  },
  {
    title: "Colonial Bungalow",
    description: "A taste of history in this colonial-era mansion.",
    image: "https://images.unsplash.com/photo-1501117716987-c8e1ecb2101f",
    price: 8700,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Desert Safari Camp",
    description: "Adventure-filled nights under the desert sky.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 3200,
    location: "Bikaner",
    country: "India",
  },
  {
    title: "City Lights Apartment",
    description: "Modern apartment close to nightlife and restaurants.",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c94",
    price: 6400,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Eco-Friendly Lodge",
    description: "Sustainable stay powered by solar energy.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    price: 5200,
    location: "Sikkim",
    country: "India",
  }
];

module.exports = sampleListings;